### ISSUE TITLE
Fails on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [m-schwabe/enrol_badgeenrol#1]
Attempting to enrol as a student on PostgreSQL fails badly with the following error message. Note that MySQL is much more benevolent when it comes to input (such as empty string for the integer field) and it is recommended to test plugins on PostgreSQL, too.

```
Debug info: ERROR: invalid input syntax for integer: ""
SELECT * FROM mdl_badge_issued WHERE badgeid = $1 AND userid = $2
[array (
0 => '',
1 => '3',
)]
Error code: dmlreadexception

Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1478 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1450 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1429 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 191 of /enrol/badgeenrol/lib.php: call to moodle_database->get_record()
line 142 of /enrol/badgeenrol/lib.php: call to enrol_badgeenrol_plugin->check_required_badges()
line 72 of /enrol/index.php: call to enrol_badgeenrol_plugin->enrol_page_hook()
```

**Comment by m-schwabe** [comment]
Hello David,

thanks for posting this issue. Can it be that you just did not select a required badge for the enrolment plugin instance or even have no badges in the course?

**Comment by mudrd8mz** [comment]
The badge was selected and the plugin configured.

Anyway, even if that was the case, surely the plugin should deal with such situation in a better way than throwing database exception (which would lead to blank page on most production sites with error messages display off).

I believe the debug output pasted above and the stack trace contains enough information to track this.

**Comment by m-schwabe** [comment]
I fixed this issue. This input should now not become empty.
